### ISSUE TITLE
Косяки инсталлера

### ISSUE THREAD

**Issue by zorn-v** [Floxim/floxim-demosite#3]
1. Почему то считает что может находится только в корне DOCUMENT_ROOT
2. Зачем то нужны short_open_tags
3. При проверке memory_limit не учитывается что он вообще может быть отключен (равен -1)
4. Сразу после установки выплёвывает кучу исключений

**Comment by dubrowsky** [comment]
Привет! Инсталллером очень давно не пользовались, спасибо за баги.
1. document root, кажется, пока нужен - админка генерирует абсолютные URL.
2. short_open_tags давно не нужны, поправим.
3. Поправим.
4. Демо-сайт сильно отстал от самой цмски, когда будем готовить полноценный релиз - обязательно приведем в порядок. Сейчас мы хотели показать только пользовательский интерфейс.

**Comment by zorn-v** [comment]
1. Я про другое. Во первых - header('Location: /install/'). А если я хочу установить например в /floxima/ ?
   Плюс все проверки (возможность записи, расположения конфига и т.п.) так же считаются от DOCUMENT_ROOT

**Comment by zorn-v** [comment]
Если роутер работает тоже только от корня, то все пичально...

**Comment by dubrowsky** [comment]
Да, именно так - роутер работает от корня. Приведете, пожалуйста, понятный кейс, когда действительно нужна установка в субдиректорию. Я знаю такие:
1.  У разработчика есть один единственный http://localhost/ - и он ставит туда все, что найдет.
2. Маленькие лендинги/спецпроекты на большом сайте.

Первое лечится установкой нормального wamp-пакета ("w" - потому что для *nix это какая-то совсем странная проблема).
Второе актуально, но в весьма отдаленной перспективе.

Сделать вроде не очень сложно, пути записываются через алиасы в стиле Yii. Хотелось бы заранее понять, зачем =)

**Comment by zorn-v** [comment]
В моем случае это был тестовый сервер LAMP, на котором по быстрому разворачиваются всякие штуки (на посмотреть и/или допилить) тупо копированием в папку.
Не понятно почему для *nix это проблема странная. Вы предлагаете на каждый такой тест копание в конфигах впридачу ? Учитывая что подобной болезнью на моей памяти никто не страдал. Можно конечно и php -S 0.0.0.0:8000 на крайняк, но на мой взгляд это явная недоработка - не важно для чего это может понадобится. Другие же не задаются этим вопросом, а сразу делают _правильно_
А в голове был кейз из пункта 2 когда писал что это все таки "проблема" :)
